USER: melanmeg
TARGET_BRANCH: main

# kube v1.31
# INSTALL_KUBE_VERSION: 1.31.0-1.1
# KUBE_VERSION: 1.31.0

# kube v1.30
INSTALL_KUBE_VERSION: 1.30.4-1.1
KUBE_VERSION: 1.30.4

# Containerd V2
# CRI_SOCKET_PATH: /run/containerd/containerd.sock

# Containerd V1
CRI_SOCKET_PATH: /var/run/containerd/containerd.sock

KUBE_API_SERVER_VIP: 192.168.11.110
NODE_IP_1: 192.168.11.114
NODE_IP_2: 192.168.11.115
NODE_IP_3: 192.168.11.116
